baseURL = 'https://noelle-it.com/'
languageCode = 'de-de'
title = 'Noelle IT'
theme = 'PaperMod'

[markup.goldmark.renderer]
    unsafe = true # Ermöglicht das Einbinden des Impressum-Scripts

[params]
    env = 'production'
    description = 'Professionelle Billbee Einrichtung und Optimierung für Ihren E-Commerce'
    author = 'Jonas Nölle'
    ShowCodeCopyButtons = true

    [params.profileMode]
        enabled = true
    title = "E-Commerce Automatisierung mit System"
    subtitle = "Ich helfe Online-Händlern, ihre Billbee-Prozesse zu perfektionieren. Mehr Zeit für Ihr Business – weniger Stress mit der Technik."
        
        [[params.profileMode.buttons]]
            name = 'Leistungen ansehen'
            url = '/leistungen/'

        [[params.profileMode.buttons]]
            name = 'Kontakt aufnehmen'
            url = 'mailto:anfrage@noelle-it.com'

    [[params.socialIcons]]
        name = 'email'
        url = 'mailto:anfrage@noelle-it.com'

[menu]
    [[menu.main]]
        name = 'Leistungen'
        url = '/leistungen/'
        weight = 10

    [[menu.main]]
        name = 'Impressum'
        url = '/impressum/'
        weight = 20
        
    [[menu.main]]
    name = "Datenschutz"
    url = "/datenschutz/"
    weight = 30    
