baseURL = 'https://noelle-it.com/'
languageCode = 'de-de'
title = 'Noelle IT'
theme = 'PaperMod'

[markup.goldmark.renderer]
    unsafe = true # Erlaubt das Impressum-Script der IT-Recht-Kanzlei

[params]
    env = 'production'
    description = 'Professionelle Billbee Einrichtung und Optimierung'
    author = 'Jonas Nölle'

    [params.profileMode]
        enabled = true
        title = 'Noelle IT'
        subtitle = 'Ihr Billbee Partner für reibungslose E-Commerce-Prozesse.'
        
        [[params.profileMode.buttons]]
            name = 'Leistungen ansehen'
            url = '/leistungen'

        [[params.profileMode.buttons]]
            name = 'Kontakt aufnehmen'
            url = 'mailto:anfrage@noelle-it.com'

    [[params.socialIcons]]
        name = 'email'
        url = 'mailto:anfrage@noelle-it.com'

[menu]
    [[menu.main]]
        name = 'Leistungen'
        url = '/leistungen/'
        weight = 10

    [[menu.main]]
        name = 'Impressum'
        url = '/impressum/'
        weight = 20
